pub const GET: &str = "GET";
pub const POST: &str = "POST";
pub const PUT: &str = "PUT";
pub const DELETE: &str = "DELETE";
pub const PATCH: &str = "PATCH";
pub const HEAD: &str = "HEAD";
pub const OPTIONS: &str = "OPTIONS";
pub const CONNECT: &str = "CONNECT";
pub const TRACE: &str = "TRACE";
pub const GET_POST: &str = "GET, POST";
pub const GET_PUT: &str = "GET, PUT";
pub const GET_DELETE: &str = "GET, DELETE";
pub const GET_PATCH: &str = "GET, PATCH";
pub const GET_HEAD: &str = "GET, HEAD";
pub const GET_OPTIONS: &str = "GET, OPTIONS";
pub const GET_CONNECT: &str = "GET, CONNECT";
pub const GET_TRACE: &str = "GET, TRACE";
pub const POST_PUT: &str = "POST, PUT";
pub const POST_DELETE: &str = "POST, DELETE";
pub const POST_PATCH: &str = "POST, PATCH";
pub const POST_HEAD: &str = "POST, HEAD";
pub const POST_OPTIONS: &str = "POST, OPTIONS";
pub const POST_CONNECT: &str = "POST, CONNECT";
pub const POST_TRACE: &str = "POST, TRACE";
pub const PUT_DELETE: &str = "PUT, DELETE";
pub const PUT_PATCH: &str = "PUT, PATCH";
pub const PUT_HEAD: &str = "PUT, HEAD";
pub const PUT_OPTIONS: &str = "PUT, OPTIONS";
pub const PUT_CONNECT: &str = "PUT, CONNECT";
pub const PUT_TRACE: &str = "PUT, TRACE";
pub const DELETE_PATCH: &str = "DELETE, PATCH";
pub const DELETE_HEAD: &str = "DELETE, HEAD";
pub const DELETE_OPTIONS: &str = "DELETE, OPTIONS";
pub const DELETE_CONNECT: &str = "DELETE, CONNECT";
pub const DELETE_TRACE: &str = "DELETE, TRACE";
pub const PATCH_HEAD: &str = "PATCH, HEAD";
pub const PATCH_OPTIONS: &str = "PATCH, OPTIONS";
pub const PATCH_CONNECT: &str = "PATCH, CONNECT";
pub const PATCH_TRACE: &str = "PATCH, TRACE";
pub const HEAD_OPTIONS: &str = "HEAD, OPTIONS";
pub const HEAD_CONNECT: &str = "HEAD, CONNECT";
pub const HEAD_TRACE: &str = "HEAD, TRACE";
pub const OPTIONS_CONNECT: &str = "OPTIONS, CONNECT";
pub const OPTIONS_TRACE: &str = "OPTIONS, TRACE";
pub const CONNECT_TRACE: &str = "CONNECT, TRACE";
pub const GET_POST_PUT: &str = "GET, POST, PUT";
pub const GET_POST_DELETE: &str = "GET, POST, DELETE";
pub const GET_POST_PATCH: &str = "GET, POST, PATCH";
pub const GET_POST_HEAD: &str = "GET, POST, HEAD";
pub const GET_POST_OPTIONS: &str = "GET, POST, OPTIONS";
pub const GET_POST_CONNECT: &str = "GET, POST, CONNECT";
pub const GET_POST_TRACE: &str = "GET, POST, TRACE";
pub const GET_PUT_DELETE: &str = "GET, PUT, DELETE";
pub const GET_PUT_PATCH: &str = "GET, PUT, PATCH";
pub const GET_PUT_HEAD: &str = "GET, PUT, HEAD";
pub const GET_PUT_OPTIONS: &str = "GET, PUT, OPTIONS";
pub const GET_PUT_CONNECT: &str = "GET, PUT, CONNECT";
pub const GET_PUT_TRACE: &str = "GET, PUT, TRACE";
pub const GET_DELETE_PATCH: &str = "GET, DELETE, PATCH";
pub const GET_DELETE_HEAD: &str = "GET, DELETE, HEAD";
pub const GET_DELETE_OPTIONS: &str = "GET, DELETE, OPTIONS";
pub const GET_DELETE_CONNECT: &str = "GET, DELETE, CONNECT";
pub const GET_DELETE_TRACE: &str = "GET, DELETE, TRACE";
pub const GET_PATCH_HEAD: &str = "GET, PATCH, HEAD";
pub const GET_PATCH_OPTIONS: &str = "GET, PATCH, OPTIONS";
pub const GET_PATCH_CONNECT: &str = "GET, PATCH, CONNECT";
pub const GET_PATCH_TRACE: &str = "GET, PATCH, TRACE";
pub const GET_HEAD_OPTIONS: &str = "GET, HEAD, OPTIONS";
pub const GET_HEAD_CONNECT: &str = "GET, HEAD, CONNECT";
pub const GET_HEAD_TRACE: &str = "GET, HEAD, TRACE";
pub const GET_OPTIONS_CONNECT: &str = "GET, OPTIONS, CONNECT";
pub const GET_OPTIONS_TRACE: &str = "GET, OPTIONS, TRACE";
pub const GET_CONNECT_TRACE: &str = "GET, CONNECT, TRACE";
pub const POST_PUT_DELETE: &str = "POST, PUT, DELETE";
pub const POST_PUT_PATCH: &str = "POST, PUT, PATCH";
pub const POST_PUT_HEAD: &str = "POST, PUT, HEAD";
pub const POST_PUT_OPTIONS: &str = "POST, PUT, OPTIONS";
pub const POST_PUT_CONNECT: &str = "POST, PUT, CONNECT";
pub const POST_PUT_TRACE: &str = "POST, PUT, TRACE";
pub const POST_DELETE_PATCH: &str = "POST, DELETE, PATCH";
pub const POST_DELETE_HEAD: &str = "POST, DELETE, HEAD";
pub const POST_DELETE_OPTIONS: &str = "POST, DELETE, OPTIONS";
pub const POST_DELETE_CONNECT: &str = "POST, DELETE, CONNECT";
pub const POST_DELETE_TRACE: &str = "POST, DELETE, TRACE";
pub const POST_PATCH_HEAD: &str = "POST, PATCH, HEAD";
pub const POST_PATCH_OPTIONS: &str = "POST, PATCH, OPTIONS";
pub const POST_PATCH_CONNECT: &str = "POST, PATCH, CONNECT";
pub const POST_PATCH_TRACE: &str = "POST, PATCH, TRACE";
pub const POST_HEAD_OPTIONS: &str = "POST, HEAD, OPTIONS";
pub const POST_HEAD_CONNECT: &str = "POST, HEAD, CONNECT";
pub const POST_HEAD_TRACE: &str = "POST, HEAD, TRACE";
pub const POST_OPTIONS_CONNECT: &str = "POST, OPTIONS, CONNECT";
pub const POST_OPTIONS_TRACE: &str = "POST, OPTIONS, TRACE";
pub const POST_CONNECT_TRACE: &str = "POST, CONNECT, TRACE";
pub const PUT_DELETE_PATCH: &str = "PUT, DELETE, PATCH";
pub const PUT_DELETE_HEAD: &str = "PUT, DELETE, HEAD";
pub const PUT_DELETE_OPTIONS: &str = "PUT, DELETE, OPTIONS";
pub const PUT_DELETE_CONNECT: &str = "PUT, DELETE, CONNECT";
pub const PUT_DELETE_TRACE: &str = "PUT, DELETE, TRACE";
pub const PUT_PATCH_HEAD: &str = "PUT, PATCH, HEAD";
pub const PUT_PATCH_OPTIONS: &str = "PUT, PATCH, OPTIONS";
pub const PUT_PATCH_CONNECT: &str = "PUT, PATCH, CONNECT";
pub const PUT_PATCH_TRACE: &str = "PUT, PATCH, TRACE";
pub const PUT_HEAD_OPTIONS: &str = "PUT, HEAD, OPTIONS";
pub const PUT_HEAD_CONNECT: &str = "PUT, HEAD, CONNECT";
pub const PUT_HEAD_TRACE: &str = "PUT, HEAD, TRACE";
pub const PUT_OPTIONS_CONNECT: &str = "PUT, OPTIONS, CONNECT";
pub const PUT_OPTIONS_TRACE: &str = "PUT, OPTIONS, TRACE";
pub const PUT_CONNECT_TRACE: &str = "PUT, CONNECT, TRACE";
pub const DELETE_PATCH_HEAD: &str = "DELETE, PATCH, HEAD";
pub const DELETE_PATCH_OPTIONS: &str = "DELETE, PATCH, OPTIONS";
pub const DELETE_PATCH_CONNECT: &str = "DELETE, PATCH, CONNECT";
pub const DELETE_PATCH_TRACE: &str = "DELETE, PATCH, TRACE";
pub const DELETE_HEAD_OPTIONS: &str = "DELETE, HEAD, OPTIONS";
pub const DELETE_HEAD_CONNECT: &str = "DELETE, HEAD, CONNECT";
pub const DELETE_HEAD_TRACE: &str = "DELETE, HEAD, TRACE";
pub const DELETE_OPTIONS_CONNECT: &str = "DELETE, OPTIONS, CONNECT";
pub const DELETE_OPTIONS_TRACE: &str = "DELETE, OPTIONS, TRACE";
pub const DELETE_CONNECT_TRACE: &str = "DELETE, CONNECT, TRACE";
pub const PATCH_HEAD_OPTIONS: &str = "PATCH, HEAD, OPTIONS";
pub const PATCH_HEAD_CONNECT: &str = "PATCH, HEAD, CONNECT";
pub const PATCH_HEAD_TRACE: &str = "PATCH, HEAD, TRACE";
pub const PATCH_OPTIONS_CONNECT: &str = "PATCH, OPTIONS, CONNECT";
pub const PATCH_OPTIONS_TRACE: &str = "PATCH, OPTIONS, TRACE";
pub const PATCH_CONNECT_TRACE: &str = "PATCH, CONNECT, TRACE";
pub const HEAD_OPTIONS_CONNECT: &str = "HEAD, OPTIONS, CONNECT";
pub const HEAD_OPTIONS_TRACE: &str = "HEAD, OPTIONS, TRACE";
pub const HEAD_CONNECT_TRACE: &str = "HEAD, CONNECT, TRACE";
pub const OPTIONS_CONNECT_TRACE: &str = "OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE: &str = "GET, POST, PUT, DELETE";
pub const GET_POST_PUT_PATCH: &str = "GET, POST, PUT, PATCH";
pub const GET_POST_PUT_HEAD: &str = "GET, POST, PUT, HEAD";
pub const GET_POST_PUT_OPTIONS: &str = "GET, POST, PUT, OPTIONS";
pub const GET_POST_PUT_CONNECT: &str = "GET, POST, PUT, CONNECT";
pub const GET_POST_PUT_TRACE: &str = "GET, POST, PUT, TRACE";
pub const GET_POST_DELETE_PATCH: &str = "GET, POST, DELETE, PATCH";
pub const GET_POST_DELETE_HEAD: &str = "GET, POST, DELETE, HEAD";
pub const GET_POST_DELETE_OPTIONS: &str = "GET, POST, DELETE, OPTIONS";
pub const GET_POST_DELETE_CONNECT: &str = "GET, POST, DELETE, CONNECT";
pub const GET_POST_DELETE_TRACE: &str = "GET, POST, DELETE, TRACE";
pub const GET_POST_PATCH_HEAD: &str = "GET, POST, PATCH, HEAD";
pub const GET_POST_PATCH_OPTIONS: &str = "GET, POST, PATCH, OPTIONS";
pub const GET_POST_PATCH_CONNECT: &str = "GET, POST, PATCH, CONNECT";
pub const GET_POST_PATCH_TRACE: &str = "GET, POST, PATCH, TRACE";
pub const GET_POST_HEAD_OPTIONS: &str = "GET, POST, HEAD, OPTIONS";
pub const GET_POST_HEAD_CONNECT: &str = "GET, POST, HEAD, CONNECT";
pub const GET_POST_HEAD_TRACE: &str = "GET, POST, HEAD, TRACE";
pub const GET_POST_OPTIONS_CONNECT: &str = "GET, POST, OPTIONS, CONNECT";
pub const GET_POST_OPTIONS_TRACE: &str = "GET, POST, OPTIONS, TRACE";
pub const GET_POST_CONNECT_TRACE: &str = "GET, POST, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH: &str = "GET, PUT, DELETE, PATCH";
pub const GET_PUT_DELETE_HEAD: &str = "GET, PUT, DELETE, HEAD";
pub const GET_PUT_DELETE_OPTIONS: &str = "GET, PUT, DELETE, OPTIONS";
pub const GET_PUT_DELETE_CONNECT: &str = "GET, PUT, DELETE, CONNECT";
pub const GET_PUT_DELETE_TRACE: &str = "GET, PUT, DELETE, TRACE";
pub const GET_PUT_PATCH_HEAD: &str = "GET, PUT, PATCH, HEAD";
pub const GET_PUT_PATCH_OPTIONS: &str = "GET, PUT, PATCH, OPTIONS";
pub const GET_PUT_PATCH_CONNECT: &str = "GET, PUT, PATCH, CONNECT";
pub const GET_PUT_PATCH_TRACE: &str = "GET, PUT, PATCH, TRACE";
pub const GET_PUT_HEAD_OPTIONS: &str = "GET, PUT, HEAD, OPTIONS";
pub const GET_PUT_HEAD_CONNECT: &str = "GET, PUT, HEAD, CONNECT";
pub const GET_PUT_HEAD_TRACE: &str = "GET, PUT, HEAD, TRACE";
pub const GET_PUT_OPTIONS_CONNECT: &str = "GET, PUT, OPTIONS, CONNECT";
pub const GET_PUT_OPTIONS_TRACE: &str = "GET, PUT, OPTIONS, TRACE";
pub const GET_PUT_CONNECT_TRACE: &str = "GET, PUT, CONNECT, TRACE";
pub const GET_DELETE_PATCH_HEAD: &str = "GET, DELETE, PATCH, HEAD";
pub const GET_DELETE_PATCH_OPTIONS: &str = "GET, DELETE, PATCH, OPTIONS";
pub const GET_DELETE_PATCH_CONNECT: &str = "GET, DELETE, PATCH, CONNECT";
pub const GET_DELETE_PATCH_TRACE: &str = "GET, DELETE, PATCH, TRACE";
pub const GET_DELETE_HEAD_OPTIONS: &str = "GET, DELETE, HEAD, OPTIONS";
pub const GET_DELETE_HEAD_CONNECT: &str = "GET, DELETE, HEAD, CONNECT";
pub const GET_DELETE_HEAD_TRACE: &str = "GET, DELETE, HEAD, TRACE";
pub const GET_DELETE_OPTIONS_CONNECT: &str = "GET, DELETE, OPTIONS, CONNECT";
pub const GET_DELETE_OPTIONS_TRACE: &str = "GET, DELETE, OPTIONS, TRACE";
pub const GET_DELETE_CONNECT_TRACE: &str = "GET, DELETE, CONNECT, TRACE";
pub const GET_PATCH_HEAD_OPTIONS: &str = "GET, PATCH, HEAD, OPTIONS";
pub const GET_PATCH_HEAD_CONNECT: &str = "GET, PATCH, HEAD, CONNECT";
pub const GET_PATCH_HEAD_TRACE: &str = "GET, PATCH, HEAD, TRACE";
pub const GET_PATCH_OPTIONS_CONNECT: &str = "GET, PATCH, OPTIONS, CONNECT";
pub const GET_PATCH_OPTIONS_TRACE: &str = "GET, PATCH, OPTIONS, TRACE";
pub const GET_PATCH_CONNECT_TRACE: &str = "GET, PATCH, CONNECT, TRACE";
pub const GET_HEAD_OPTIONS_CONNECT: &str = "GET, HEAD, OPTIONS, CONNECT";
pub const GET_HEAD_OPTIONS_TRACE: &str = "GET, HEAD, OPTIONS, TRACE";
pub const GET_HEAD_CONNECT_TRACE: &str = "GET, HEAD, CONNECT, TRACE";
pub const GET_OPTIONS_CONNECT_TRACE: &str = "GET, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH: &str = "POST, PUT, DELETE, PATCH";
pub const POST_PUT_DELETE_HEAD: &str = "POST, PUT, DELETE, HEAD";
pub const POST_PUT_DELETE_OPTIONS: &str = "POST, PUT, DELETE, OPTIONS";
pub const POST_PUT_DELETE_CONNECT: &str = "POST, PUT, DELETE, CONNECT";
pub const POST_PUT_DELETE_TRACE: &str = "POST, PUT, DELETE, TRACE";
pub const POST_PUT_PATCH_HEAD: &str = "POST, PUT, PATCH, HEAD";
pub const POST_PUT_PATCH_OPTIONS: &str = "POST, PUT, PATCH, OPTIONS";
pub const POST_PUT_PATCH_CONNECT: &str = "POST, PUT, PATCH, CONNECT";
pub const POST_PUT_PATCH_TRACE: &str = "POST, PUT, PATCH, TRACE";
pub const POST_PUT_HEAD_OPTIONS: &str = "POST, PUT, HEAD, OPTIONS";
pub const POST_PUT_HEAD_CONNECT: &str = "POST, PUT, HEAD, CONNECT";
pub const POST_PUT_HEAD_TRACE: &str = "POST, PUT, HEAD, TRACE";
pub const POST_PUT_OPTIONS_CONNECT: &str = "POST, PUT, OPTIONS, CONNECT";
pub const POST_PUT_OPTIONS_TRACE: &str = "POST, PUT, OPTIONS, TRACE";
pub const POST_PUT_CONNECT_TRACE: &str = "POST, PUT, CONNECT, TRACE";
pub const POST_DELETE_PATCH_HEAD: &str = "POST, DELETE, PATCH, HEAD";
pub const POST_DELETE_PATCH_OPTIONS: &str = "POST, DELETE, PATCH, OPTIONS";
pub const POST_DELETE_PATCH_CONNECT: &str = "POST, DELETE, PATCH, CONNECT";
pub const POST_DELETE_PATCH_TRACE: &str = "POST, DELETE, PATCH, TRACE";
pub const POST_DELETE_HEAD_OPTIONS: &str = "POST, DELETE, HEAD, OPTIONS";
pub const POST_DELETE_HEAD_CONNECT: &str = "POST, DELETE, HEAD, CONNECT";
pub const POST_DELETE_HEAD_TRACE: &str = "POST, DELETE, HEAD, TRACE";
pub const POST_DELETE_OPTIONS_CONNECT: &str = "POST, DELETE, OPTIONS, CONNECT";
pub const POST_DELETE_OPTIONS_TRACE: &str = "POST, DELETE, OPTIONS, TRACE";
pub const POST_DELETE_CONNECT_TRACE: &str = "POST, DELETE, CONNECT, TRACE";
pub const POST_PATCH_HEAD_OPTIONS: &str = "POST, PATCH, HEAD, OPTIONS";
pub const POST_PATCH_HEAD_CONNECT: &str = "POST, PATCH, HEAD, CONNECT";
pub const POST_PATCH_HEAD_TRACE: &str = "POST, PATCH, HEAD, TRACE";
pub const POST_PATCH_OPTIONS_CONNECT: &str = "POST, PATCH, OPTIONS, CONNECT";
pub const POST_PATCH_OPTIONS_TRACE: &str = "POST, PATCH, OPTIONS, TRACE";
pub const POST_PATCH_CONNECT_TRACE: &str = "POST, PATCH, CONNECT, TRACE";
pub const POST_HEAD_OPTIONS_CONNECT: &str = "POST, HEAD, OPTIONS, CONNECT";
pub const POST_HEAD_OPTIONS_TRACE: &str = "POST, HEAD, OPTIONS, TRACE";
pub const POST_HEAD_CONNECT_TRACE: &str = "POST, HEAD, CONNECT, TRACE";
pub const POST_OPTIONS_CONNECT_TRACE: &str = "POST, OPTIONS, CONNECT, TRACE";
pub const PUT_DELETE_PATCH_HEAD: &str = "PUT, DELETE, PATCH, HEAD";
pub const PUT_DELETE_PATCH_OPTIONS: &str = "PUT, DELETE, PATCH, OPTIONS";
pub const PUT_DELETE_PATCH_CONNECT: &str = "PUT, DELETE, PATCH, CONNECT";
pub const PUT_DELETE_PATCH_TRACE: &str = "PUT, DELETE, PATCH, TRACE";
pub const PUT_DELETE_HEAD_OPTIONS: &str = "PUT, DELETE, HEAD, OPTIONS";
pub const PUT_DELETE_HEAD_CONNECT: &str = "PUT, DELETE, HEAD, CONNECT";
pub const PUT_DELETE_HEAD_TRACE: &str = "PUT, DELETE, HEAD, TRACE";
pub const PUT_DELETE_OPTIONS_CONNECT: &str = "PUT, DELETE, OPTIONS, CONNECT";
pub const PUT_DELETE_OPTIONS_TRACE: &str = "PUT, DELETE, OPTIONS, TRACE";
pub const PUT_DELETE_CONNECT_TRACE: &str = "PUT, DELETE, CONNECT, TRACE";
pub const PUT_PATCH_HEAD_OPTIONS: &str = "PUT, PATCH, HEAD, OPTIONS";
pub const PUT_PATCH_HEAD_CONNECT: &str = "PUT, PATCH, HEAD, CONNECT";
pub const PUT_PATCH_HEAD_TRACE: &str = "PUT, PATCH, HEAD, TRACE";
pub const PUT_PATCH_OPTIONS_CONNECT: &str = "PUT, PATCH, OPTIONS, CONNECT";
pub const PUT_PATCH_OPTIONS_TRACE: &str = "PUT, PATCH, OPTIONS, TRACE";
pub const PUT_PATCH_CONNECT_TRACE: &str = "PUT, PATCH, CONNECT, TRACE";
pub const PUT_HEAD_OPTIONS_CONNECT: &str = "PUT, HEAD, OPTIONS, CONNECT";
pub const PUT_HEAD_OPTIONS_TRACE: &str = "PUT, HEAD, OPTIONS, TRACE";
pub const PUT_HEAD_CONNECT_TRACE: &str = "PUT, HEAD, CONNECT, TRACE";
pub const PUT_OPTIONS_CONNECT_TRACE: &str = "PUT, OPTIONS, CONNECT, TRACE";
pub const DELETE_PATCH_HEAD_OPTIONS: &str = "DELETE, PATCH, HEAD, OPTIONS";
pub const DELETE_PATCH_HEAD_CONNECT: &str = "DELETE, PATCH, HEAD, CONNECT";
pub const DELETE_PATCH_HEAD_TRACE: &str = "DELETE, PATCH, HEAD, TRACE";
pub const DELETE_PATCH_OPTIONS_CONNECT: &str = "DELETE, PATCH, OPTIONS, CONNECT";
pub const DELETE_PATCH_OPTIONS_TRACE: &str = "DELETE, PATCH, OPTIONS, TRACE";
pub const DELETE_PATCH_CONNECT_TRACE: &str = "DELETE, PATCH, CONNECT, TRACE";
pub const DELETE_HEAD_OPTIONS_CONNECT: &str = "DELETE, HEAD, OPTIONS, CONNECT";
pub const DELETE_HEAD_OPTIONS_TRACE: &str = "DELETE, HEAD, OPTIONS, TRACE";
pub const DELETE_HEAD_CONNECT_TRACE: &str = "DELETE, HEAD, CONNECT, TRACE";
pub const DELETE_OPTIONS_CONNECT_TRACE: &str = "DELETE, OPTIONS, CONNECT, TRACE";
pub const PATCH_HEAD_OPTIONS_CONNECT: &str = "PATCH, HEAD, OPTIONS, CONNECT";
pub const PATCH_HEAD_OPTIONS_TRACE: &str = "PATCH, HEAD, OPTIONS, TRACE";
pub const PATCH_HEAD_CONNECT_TRACE: &str = "PATCH, HEAD, CONNECT, TRACE";
pub const PATCH_OPTIONS_CONNECT_TRACE: &str = "PATCH, OPTIONS, CONNECT, TRACE";
pub const HEAD_OPTIONS_CONNECT_TRACE: &str = "HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH: &str = "GET, POST, PUT, DELETE, PATCH";
pub const GET_POST_PUT_DELETE_HEAD: &str = "GET, POST, PUT, DELETE, HEAD";
pub const GET_POST_PUT_DELETE_OPTIONS: &str = "GET, POST, PUT, DELETE, OPTIONS";
pub const GET_POST_PUT_DELETE_CONNECT: &str = "GET, POST, PUT, DELETE, CONNECT";
pub const GET_POST_PUT_DELETE_TRACE: &str = "GET, POST, PUT, DELETE, TRACE";
pub const GET_POST_PUT_PATCH_HEAD: &str = "GET, POST, PUT, PATCH, HEAD";
pub const GET_POST_PUT_PATCH_OPTIONS: &str = "GET, POST, PUT, PATCH, OPTIONS";
pub const GET_POST_PUT_PATCH_CONNECT: &str = "GET, POST, PUT, PATCH, CONNECT";
pub const GET_POST_PUT_PATCH_TRACE: &str = "GET, POST, PUT, PATCH, TRACE";
pub const GET_POST_PUT_HEAD_OPTIONS: &str = "GET, POST, PUT, HEAD, OPTIONS";
pub const GET_POST_PUT_HEAD_CONNECT: &str = "GET, POST, PUT, HEAD, CONNECT";
pub const GET_POST_PUT_HEAD_TRACE: &str = "GET, POST, PUT, HEAD, TRACE";
pub const GET_POST_PUT_OPTIONS_CONNECT: &str = "GET, POST, PUT, OPTIONS, CONNECT";
pub const GET_POST_PUT_OPTIONS_TRACE: &str = "GET, POST, PUT, OPTIONS, TRACE";
pub const GET_POST_PUT_CONNECT_TRACE: &str = "GET, POST, PUT, CONNECT, TRACE";
pub const GET_POST_DELETE_PATCH_HEAD: &str = "GET, POST, DELETE, PATCH, HEAD";
pub const GET_POST_DELETE_PATCH_OPTIONS: &str = "GET, POST, DELETE, PATCH, OPTIONS";
pub const GET_POST_DELETE_PATCH_CONNECT: &str = "GET, POST, DELETE, PATCH, CONNECT";
pub const GET_POST_DELETE_PATCH_TRACE: &str = "GET, POST, DELETE, PATCH, TRACE";
pub const GET_POST_DELETE_HEAD_OPTIONS: &str = "GET, POST, DELETE, HEAD, OPTIONS";
pub const GET_POST_DELETE_HEAD_CONNECT: &str = "GET, POST, DELETE, HEAD, CONNECT";
pub const GET_POST_DELETE_HEAD_TRACE: &str = "GET, POST, DELETE, HEAD, TRACE";
pub const GET_POST_DELETE_OPTIONS_CONNECT: &str = "GET, POST, DELETE, OPTIONS, CONNECT";
pub const GET_POST_DELETE_OPTIONS_TRACE: &str = "GET, POST, DELETE, OPTIONS, TRACE";
pub const GET_POST_DELETE_CONNECT_TRACE: &str = "GET, POST, DELETE, CONNECT, TRACE";
pub const GET_POST_PATCH_HEAD_OPTIONS: &str = "GET, POST, PATCH, HEAD, OPTIONS";
pub const GET_POST_PATCH_HEAD_CONNECT: &str = "GET, POST, PATCH, HEAD, CONNECT";
pub const GET_POST_PATCH_HEAD_TRACE: &str = "GET, POST, PATCH, HEAD, TRACE";
pub const GET_POST_PATCH_OPTIONS_CONNECT: &str = "GET, POST, PATCH, OPTIONS, CONNECT";
pub const GET_POST_PATCH_OPTIONS_TRACE: &str = "GET, POST, PATCH, OPTIONS, TRACE";
pub const GET_POST_PATCH_CONNECT_TRACE: &str = "GET, POST, PATCH, CONNECT, TRACE";
pub const GET_POST_HEAD_OPTIONS_CONNECT: &str = "GET, POST, HEAD, OPTIONS, CONNECT";
pub const GET_POST_HEAD_OPTIONS_TRACE: &str = "GET, POST, HEAD, OPTIONS, TRACE";
pub const GET_POST_HEAD_CONNECT_TRACE: &str = "GET, POST, HEAD, CONNECT, TRACE";
pub const GET_POST_OPTIONS_CONNECT_TRACE: &str = "GET, POST, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH_HEAD: &str = "GET, PUT, DELETE, PATCH, HEAD";
pub const GET_PUT_DELETE_PATCH_OPTIONS: &str = "GET, PUT, DELETE, PATCH, OPTIONS";
pub const GET_PUT_DELETE_PATCH_CONNECT: &str = "GET, PUT, DELETE, PATCH, CONNECT";
pub const GET_PUT_DELETE_PATCH_TRACE: &str = "GET, PUT, DELETE, PATCH, TRACE";
pub const GET_PUT_DELETE_HEAD_OPTIONS: &str = "GET, PUT, DELETE, HEAD, OPTIONS";
pub const GET_PUT_DELETE_HEAD_CONNECT: &str = "GET, PUT, DELETE, HEAD, CONNECT";
pub const GET_PUT_DELETE_HEAD_TRACE: &str = "GET, PUT, DELETE, HEAD, TRACE";
pub const GET_PUT_DELETE_OPTIONS_CONNECT: &str = "GET, PUT, DELETE, OPTIONS, CONNECT";
pub const GET_PUT_DELETE_OPTIONS_TRACE: &str = "GET, PUT, DELETE, OPTIONS, TRACE";
pub const GET_PUT_DELETE_CONNECT_TRACE: &str = "GET, PUT, DELETE, CONNECT, TRACE";
pub const GET_PUT_PATCH_HEAD_OPTIONS: &str = "GET, PUT, PATCH, HEAD, OPTIONS";
pub const GET_PUT_PATCH_HEAD_CONNECT: &str = "GET, PUT, PATCH, HEAD, CONNECT";
pub const GET_PUT_PATCH_HEAD_TRACE: &str = "GET, PUT, PATCH, HEAD, TRACE";
pub const GET_PUT_PATCH_OPTIONS_CONNECT: &str = "GET, PUT, PATCH, OPTIONS, CONNECT";
pub const GET_PUT_PATCH_OPTIONS_TRACE: &str = "GET, PUT, PATCH, OPTIONS, TRACE";
pub const GET_PUT_PATCH_CONNECT_TRACE: &str = "GET, PUT, PATCH, CONNECT, TRACE";
pub const GET_PUT_HEAD_OPTIONS_CONNECT: &str = "GET, PUT, HEAD, OPTIONS, CONNECT";
pub const GET_PUT_HEAD_OPTIONS_TRACE: &str = "GET, PUT, HEAD, OPTIONS, TRACE";
pub const GET_PUT_HEAD_CONNECT_TRACE: &str = "GET, PUT, HEAD, CONNECT, TRACE";
pub const GET_PUT_OPTIONS_CONNECT_TRACE: &str = "GET, PUT, OPTIONS, CONNECT, TRACE";
pub const GET_DELETE_PATCH_HEAD_OPTIONS: &str = "GET, DELETE, PATCH, HEAD, OPTIONS";
pub const GET_DELETE_PATCH_HEAD_CONNECT: &str = "GET, DELETE, PATCH, HEAD, CONNECT";
pub const GET_DELETE_PATCH_HEAD_TRACE: &str = "GET, DELETE, PATCH, HEAD, TRACE";
pub const GET_DELETE_PATCH_OPTIONS_CONNECT: &str = "GET, DELETE, PATCH, OPTIONS, CONNECT";
pub const GET_DELETE_PATCH_OPTIONS_TRACE: &str = "GET, DELETE, PATCH, OPTIONS, TRACE";
pub const GET_DELETE_PATCH_CONNECT_TRACE: &str = "GET, DELETE, PATCH, CONNECT, TRACE";
pub const GET_DELETE_HEAD_OPTIONS_CONNECT: &str = "GET, DELETE, HEAD, OPTIONS, CONNECT";
pub const GET_DELETE_HEAD_OPTIONS_TRACE: &str = "GET, DELETE, HEAD, OPTIONS, TRACE";
pub const GET_DELETE_HEAD_CONNECT_TRACE: &str = "GET, DELETE, HEAD, CONNECT, TRACE";
pub const GET_DELETE_OPTIONS_CONNECT_TRACE: &str = "GET, DELETE, OPTIONS, CONNECT, TRACE";
pub const GET_PATCH_HEAD_OPTIONS_CONNECT: &str = "GET, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_PATCH_HEAD_OPTIONS_TRACE: &str = "GET, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_PATCH_HEAD_CONNECT_TRACE: &str = "GET, PATCH, HEAD, CONNECT, TRACE";
pub const GET_PATCH_OPTIONS_CONNECT_TRACE: &str = "GET, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_HEAD_OPTIONS_CONNECT_TRACE: &str = "GET, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH_HEAD: &str = "POST, PUT, DELETE, PATCH, HEAD";
pub const POST_PUT_DELETE_PATCH_OPTIONS: &str = "POST, PUT, DELETE, PATCH, OPTIONS";
pub const POST_PUT_DELETE_PATCH_CONNECT: &str = "POST, PUT, DELETE, PATCH, CONNECT";
pub const POST_PUT_DELETE_PATCH_TRACE: &str = "POST, PUT, DELETE, PATCH, TRACE";
pub const POST_PUT_DELETE_HEAD_OPTIONS: &str = "POST, PUT, DELETE, HEAD, OPTIONS";
pub const POST_PUT_DELETE_HEAD_CONNECT: &str = "POST, PUT, DELETE, HEAD, CONNECT";
pub const POST_PUT_DELETE_HEAD_TRACE: &str = "POST, PUT, DELETE, HEAD, TRACE";
pub const POST_PUT_DELETE_OPTIONS_CONNECT: &str = "POST, PUT, DELETE, OPTIONS, CONNECT";
pub const POST_PUT_DELETE_OPTIONS_TRACE: &str = "POST, PUT, DELETE, OPTIONS, TRACE";
pub const POST_PUT_DELETE_CONNECT_TRACE: &str = "POST, PUT, DELETE, CONNECT, TRACE";
pub const POST_PUT_PATCH_HEAD_OPTIONS: &str = "POST, PUT, PATCH, HEAD, OPTIONS";
pub const POST_PUT_PATCH_HEAD_CONNECT: &str = "POST, PUT, PATCH, HEAD, CONNECT";
pub const POST_PUT_PATCH_HEAD_TRACE: &str = "POST, PUT, PATCH, HEAD, TRACE";
pub const POST_PUT_PATCH_OPTIONS_CONNECT: &str = "POST, PUT, PATCH, OPTIONS, CONNECT";
pub const POST_PUT_PATCH_OPTIONS_TRACE: &str = "POST, PUT, PATCH, OPTIONS, TRACE";
pub const POST_PUT_PATCH_CONNECT_TRACE: &str = "POST, PUT, PATCH, CONNECT, TRACE";
pub const POST_PUT_HEAD_OPTIONS_CONNECT: &str = "POST, PUT, HEAD, OPTIONS, CONNECT";
pub const POST_PUT_HEAD_OPTIONS_TRACE: &str = "POST, PUT, HEAD, OPTIONS, TRACE";
pub const POST_PUT_HEAD_CONNECT_TRACE: &str = "POST, PUT, HEAD, CONNECT, TRACE";
pub const POST_PUT_OPTIONS_CONNECT_TRACE: &str = "POST, PUT, OPTIONS, CONNECT, TRACE";
pub const POST_DELETE_PATCH_HEAD_OPTIONS: &str = "POST, DELETE, PATCH, HEAD, OPTIONS";
pub const POST_DELETE_PATCH_HEAD_CONNECT: &str = "POST, DELETE, PATCH, HEAD, CONNECT";
pub const POST_DELETE_PATCH_HEAD_TRACE: &str = "POST, DELETE, PATCH, HEAD, TRACE";
pub const POST_DELETE_PATCH_OPTIONS_CONNECT: &str = "POST, DELETE, PATCH, OPTIONS, CONNECT";
pub const POST_DELETE_PATCH_OPTIONS_TRACE: &str = "POST, DELETE, PATCH, OPTIONS, TRACE";
pub const POST_DELETE_PATCH_CONNECT_TRACE: &str = "POST, DELETE, PATCH, CONNECT, TRACE";
pub const POST_DELETE_HEAD_OPTIONS_CONNECT: &str = "POST, DELETE, HEAD, OPTIONS, CONNECT";
pub const POST_DELETE_HEAD_OPTIONS_TRACE: &str = "POST, DELETE, HEAD, OPTIONS, TRACE";
pub const POST_DELETE_HEAD_CONNECT_TRACE: &str = "POST, DELETE, HEAD, CONNECT, TRACE";
pub const POST_DELETE_OPTIONS_CONNECT_TRACE: &str = "POST, DELETE, OPTIONS, CONNECT, TRACE";
pub const POST_PATCH_HEAD_OPTIONS_CONNECT: &str = "POST, PATCH, HEAD, OPTIONS, CONNECT";
pub const POST_PATCH_HEAD_OPTIONS_TRACE: &str = "POST, PATCH, HEAD, OPTIONS, TRACE";
pub const POST_PATCH_HEAD_CONNECT_TRACE: &str = "POST, PATCH, HEAD, CONNECT, TRACE";
pub const POST_PATCH_OPTIONS_CONNECT_TRACE: &str = "POST, PATCH, OPTIONS, CONNECT, TRACE";
pub const POST_HEAD_OPTIONS_CONNECT_TRACE: &str = "POST, HEAD, OPTIONS, CONNECT, TRACE";
pub const PUT_DELETE_PATCH_HEAD_OPTIONS: &str = "PUT, DELETE, PATCH, HEAD, OPTIONS";
pub const PUT_DELETE_PATCH_HEAD_CONNECT: &str = "PUT, DELETE, PATCH, HEAD, CONNECT";
pub const PUT_DELETE_PATCH_HEAD_TRACE: &str = "PUT, DELETE, PATCH, HEAD, TRACE";
pub const PUT_DELETE_PATCH_OPTIONS_CONNECT: &str = "PUT, DELETE, PATCH, OPTIONS, CONNECT";
pub const PUT_DELETE_PATCH_OPTIONS_TRACE: &str = "PUT, DELETE, PATCH, OPTIONS, TRACE";
pub const PUT_DELETE_PATCH_CONNECT_TRACE: &str = "PUT, DELETE, PATCH, CONNECT, TRACE";
pub const PUT_DELETE_HEAD_OPTIONS_CONNECT: &str = "PUT, DELETE, HEAD, OPTIONS, CONNECT";
pub const PUT_DELETE_HEAD_OPTIONS_TRACE: &str = "PUT, DELETE, HEAD, OPTIONS, TRACE";
pub const PUT_DELETE_HEAD_CONNECT_TRACE: &str = "PUT, DELETE, HEAD, CONNECT, TRACE";
pub const PUT_DELETE_OPTIONS_CONNECT_TRACE: &str = "PUT, DELETE, OPTIONS, CONNECT, TRACE";
pub const PUT_PATCH_HEAD_OPTIONS_CONNECT: &str = "PUT, PATCH, HEAD, OPTIONS, CONNECT";
pub const PUT_PATCH_HEAD_OPTIONS_TRACE: &str = "PUT, PATCH, HEAD, OPTIONS, TRACE";
pub const PUT_PATCH_HEAD_CONNECT_TRACE: &str = "PUT, PATCH, HEAD, CONNECT, TRACE";
pub const PUT_PATCH_OPTIONS_CONNECT_TRACE: &str = "PUT, PATCH, OPTIONS, CONNECT, TRACE";
pub const PUT_HEAD_OPTIONS_CONNECT_TRACE: &str = "PUT, HEAD, OPTIONS, CONNECT, TRACE";
pub const DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str = "DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const DELETE_PATCH_HEAD_OPTIONS_TRACE: &str = "DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const DELETE_PATCH_HEAD_CONNECT_TRACE: &str = "DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str = "DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str = "DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str = "PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_HEAD: &str = "GET, POST, PUT, DELETE, PATCH, HEAD";
pub const GET_POST_PUT_DELETE_PATCH_OPTIONS: &str = "GET, POST, PUT, DELETE, PATCH, OPTIONS";
pub const GET_POST_PUT_DELETE_PATCH_CONNECT: &str = "GET, POST, PUT, DELETE, PATCH, CONNECT";
pub const GET_POST_PUT_DELETE_PATCH_TRACE: &str = "GET, POST, PUT, DELETE, PATCH, TRACE";
pub const GET_POST_PUT_DELETE_HEAD_OPTIONS: &str = "GET, POST, PUT, DELETE, HEAD, OPTIONS";
pub const GET_POST_PUT_DELETE_HEAD_CONNECT: &str = "GET, POST, PUT, DELETE, HEAD, CONNECT";
pub const GET_POST_PUT_DELETE_HEAD_TRACE: &str = "GET, POST, PUT, DELETE, HEAD, TRACE";
pub const GET_POST_PUT_DELETE_OPTIONS_CONNECT: &str = "GET, POST, PUT, DELETE, OPTIONS, CONNECT";
pub const GET_POST_PUT_DELETE_OPTIONS_TRACE: &str = "GET, POST, PUT, DELETE, OPTIONS, TRACE";
pub const GET_POST_PUT_DELETE_CONNECT_TRACE: &str = "GET, POST, PUT, DELETE, CONNECT, TRACE";
pub const GET_POST_PUT_PATCH_HEAD_OPTIONS: &str = "GET, POST, PUT, PATCH, HEAD, OPTIONS";
pub const GET_POST_PUT_PATCH_HEAD_CONNECT: &str = "GET, POST, PUT, PATCH, HEAD, CONNECT";
pub const GET_POST_PUT_PATCH_HEAD_TRACE: &str = "GET, POST, PUT, PATCH, HEAD, TRACE";
pub const GET_POST_PUT_PATCH_OPTIONS_CONNECT: &str = "GET, POST, PUT, PATCH, OPTIONS, CONNECT";
pub const GET_POST_PUT_PATCH_OPTIONS_TRACE: &str = "GET, POST, PUT, PATCH, OPTIONS, TRACE";
pub const GET_POST_PUT_PATCH_CONNECT_TRACE: &str = "GET, POST, PUT, PATCH, CONNECT, TRACE";
pub const GET_POST_PUT_HEAD_OPTIONS_CONNECT: &str = "GET, POST, PUT, HEAD, OPTIONS, CONNECT";
pub const GET_POST_PUT_HEAD_OPTIONS_TRACE: &str = "GET, POST, PUT, HEAD, OPTIONS, TRACE";
pub const GET_POST_PUT_HEAD_CONNECT_TRACE: &str = "GET, POST, PUT, HEAD, CONNECT, TRACE";
pub const GET_POST_PUT_OPTIONS_CONNECT_TRACE: &str = "GET, POST, PUT, OPTIONS, CONNECT, TRACE";
pub const GET_POST_DELETE_PATCH_HEAD_OPTIONS: &str = "GET, POST, DELETE, PATCH, HEAD, OPTIONS";
pub const GET_POST_DELETE_PATCH_HEAD_CONNECT: &str = "GET, POST, DELETE, PATCH, HEAD, CONNECT";
pub const GET_POST_DELETE_PATCH_HEAD_TRACE: &str = "GET, POST, DELETE, PATCH, HEAD, TRACE";
pub const GET_POST_DELETE_PATCH_OPTIONS_CONNECT: &str =
    "GET, POST, DELETE, PATCH, OPTIONS, CONNECT";
pub const GET_POST_DELETE_PATCH_OPTIONS_TRACE: &str = "GET, POST, DELETE, PATCH, OPTIONS, TRACE";
pub const GET_POST_DELETE_PATCH_CONNECT_TRACE: &str = "GET, POST, DELETE, PATCH, CONNECT, TRACE";
pub const GET_POST_DELETE_HEAD_OPTIONS_CONNECT: &str = "GET, POST, DELETE, HEAD, OPTIONS, CONNECT";
pub const GET_POST_DELETE_HEAD_OPTIONS_TRACE: &str = "GET, POST, DELETE, HEAD, OPTIONS, TRACE";
pub const GET_POST_DELETE_HEAD_CONNECT_TRACE: &str = "GET, POST, DELETE, HEAD, CONNECT, TRACE";
pub const GET_POST_DELETE_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, DELETE, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PATCH_HEAD_OPTIONS_CONNECT: &str = "GET, POST, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_POST_PATCH_HEAD_OPTIONS_TRACE: &str = "GET, POST, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_POST_PATCH_HEAD_CONNECT_TRACE: &str = "GET, POST, PATCH, HEAD, CONNECT, TRACE";
pub const GET_POST_PATCH_OPTIONS_CONNECT_TRACE: &str = "GET, POST, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_POST_HEAD_OPTIONS_CONNECT_TRACE: &str = "GET, POST, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH_HEAD_OPTIONS: &str = "GET, PUT, DELETE, PATCH, HEAD, OPTIONS";
pub const GET_PUT_DELETE_PATCH_HEAD_CONNECT: &str = "GET, PUT, DELETE, PATCH, HEAD, CONNECT";
pub const GET_PUT_DELETE_PATCH_HEAD_TRACE: &str = "GET, PUT, DELETE, PATCH, HEAD, TRACE";
pub const GET_PUT_DELETE_PATCH_OPTIONS_CONNECT: &str = "GET, PUT, DELETE, PATCH, OPTIONS, CONNECT";
pub const GET_PUT_DELETE_PATCH_OPTIONS_TRACE: &str = "GET, PUT, DELETE, PATCH, OPTIONS, TRACE";
pub const GET_PUT_DELETE_PATCH_CONNECT_TRACE: &str = "GET, PUT, DELETE, PATCH, CONNECT, TRACE";
pub const GET_PUT_DELETE_HEAD_OPTIONS_CONNECT: &str = "GET, PUT, DELETE, HEAD, OPTIONS, CONNECT";
pub const GET_PUT_DELETE_HEAD_OPTIONS_TRACE: &str = "GET, PUT, DELETE, HEAD, OPTIONS, TRACE";
pub const GET_PUT_DELETE_HEAD_CONNECT_TRACE: &str = "GET, PUT, DELETE, HEAD, CONNECT, TRACE";
pub const GET_PUT_DELETE_OPTIONS_CONNECT_TRACE: &str = "GET, PUT, DELETE, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_PATCH_HEAD_OPTIONS_CONNECT: &str = "GET, PUT, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_PUT_PATCH_HEAD_OPTIONS_TRACE: &str = "GET, PUT, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_PUT_PATCH_HEAD_CONNECT_TRACE: &str = "GET, PUT, PATCH, HEAD, CONNECT, TRACE";
pub const GET_PUT_PATCH_OPTIONS_CONNECT_TRACE: &str = "GET, PUT, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_HEAD_OPTIONS_CONNECT_TRACE: &str = "GET, PUT, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "GET, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str = "GET, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_DELETE_PATCH_HEAD_CONNECT_TRACE: &str = "GET, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const GET_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "GET, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str = "GET, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH_HEAD_OPTIONS: &str = "POST, PUT, DELETE, PATCH, HEAD, OPTIONS";
pub const POST_PUT_DELETE_PATCH_HEAD_CONNECT: &str = "POST, PUT, DELETE, PATCH, HEAD, CONNECT";
pub const POST_PUT_DELETE_PATCH_HEAD_TRACE: &str = "POST, PUT, DELETE, PATCH, HEAD, TRACE";
pub const POST_PUT_DELETE_PATCH_OPTIONS_CONNECT: &str =
    "POST, PUT, DELETE, PATCH, OPTIONS, CONNECT";
pub const POST_PUT_DELETE_PATCH_OPTIONS_TRACE: &str = "POST, PUT, DELETE, PATCH, OPTIONS, TRACE";
pub const POST_PUT_DELETE_PATCH_CONNECT_TRACE: &str = "POST, PUT, DELETE, PATCH, CONNECT, TRACE";
pub const POST_PUT_DELETE_HEAD_OPTIONS_CONNECT: &str = "POST, PUT, DELETE, HEAD, OPTIONS, CONNECT";
pub const POST_PUT_DELETE_HEAD_OPTIONS_TRACE: &str = "POST, PUT, DELETE, HEAD, OPTIONS, TRACE";
pub const POST_PUT_DELETE_HEAD_CONNECT_TRACE: &str = "POST, PUT, DELETE, HEAD, CONNECT, TRACE";
pub const POST_PUT_DELETE_OPTIONS_CONNECT_TRACE: &str =
    "POST, PUT, DELETE, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_PATCH_HEAD_OPTIONS_CONNECT: &str = "POST, PUT, PATCH, HEAD, OPTIONS, CONNECT";
pub const POST_PUT_PATCH_HEAD_OPTIONS_TRACE: &str = "POST, PUT, PATCH, HEAD, OPTIONS, TRACE";
pub const POST_PUT_PATCH_HEAD_CONNECT_TRACE: &str = "POST, PUT, PATCH, HEAD, CONNECT, TRACE";
pub const POST_PUT_PATCH_OPTIONS_CONNECT_TRACE: &str = "POST, PUT, PATCH, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_HEAD_OPTIONS_CONNECT_TRACE: &str = "POST, PUT, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "POST, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const POST_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str = "POST, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const POST_DELETE_PATCH_HEAD_CONNECT_TRACE: &str = "POST, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const POST_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "POST, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const POST_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const PUT_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str = "PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const PUT_DELETE_PATCH_HEAD_CONNECT_TRACE: &str = "PUT, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const PUT_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "PUT, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const PUT_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "PUT, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const PUT_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str = "PUT, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_OPTIONS: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_CONNECT: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, CONNECT";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_TRACE: &str = "GET, POST, PUT, DELETE, PATCH, HEAD, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_OPTIONS_CONNECT: &str =
    "GET, POST, PUT, DELETE, PATCH, OPTIONS, CONNECT";
pub const GET_POST_PUT_DELETE_PATCH_OPTIONS_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, OPTIONS, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_HEAD_OPTIONS_CONNECT: &str =
    "GET, POST, PUT, DELETE, HEAD, OPTIONS, CONNECT";
pub const GET_POST_PUT_DELETE_HEAD_OPTIONS_TRACE: &str =
    "GET, POST, PUT, DELETE, HEAD, OPTIONS, TRACE";
pub const GET_POST_PUT_DELETE_HEAD_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, HEAD, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "GET, POST, PUT, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_POST_PUT_PATCH_HEAD_OPTIONS_TRACE: &str =
    "GET, POST, PUT, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_POST_PUT_PATCH_HEAD_CONNECT_TRACE: &str =
    "GET, POST, PUT, PATCH, HEAD, CONNECT, TRACE";
pub const GET_POST_PUT_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "GET, POST, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_POST_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str =
    "GET, POST, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_POST_DELETE_PATCH_HEAD_CONNECT_TRACE: &str =
    "GET, POST, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const GET_POST_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_POST_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "GET, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_PUT_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str =
    "GET, PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_PUT_DELETE_PATCH_HEAD_CONNECT_TRACE: &str =
    "GET, PUT, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "GET, PUT, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, PUT, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, PUT, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const POST_PUT_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str =
    "POST, PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const POST_PUT_DELETE_PATCH_HEAD_CONNECT_TRACE: &str =
    "POST, PUT, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "POST, PUT, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, PUT, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, PUT, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_OPTIONS_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const POST_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const GET_POST_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE: &str =
    "GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS, CONNECT, TRACE";
pub const ALL_METHODS: &str = GET_POST_PUT_DELETE_PATCH_HEAD_OPTIONS_CONNECT_TRACE;
